### ISSUE TITLE
Stop using EKEventStore

### ISSUE THREAD

**Issue by xavierjurado** [appnexus/mobile-sdk-ios#13]
Apps compiled with AppNexus SDK will get rejected by Apple due to the usage of `-[EKEventStore requestAccessToEntityType: completion:]`, unless the key `NSCalendarsUsageDescription` is specified in the app's Info.plist.

This functionality should be removed, documented and/or made optional (eg: through the usage of a subspec) so apps are not **forced** to include the `NSCalendarsUsageDescription`.

**Comment by josecu** [comment]
Thanks for bringing this issue to our attention. Our engineering team will look into handling it in a future release. In the meantime, you can removing calendar (and picture) MRAID support on your own fork of the SDK by modifying three different classes:

- ANMRAIDCalendarManager.h
- ANMRAIDCalendarManager.m
- ANMRAIDUtil.m

I’ve attached the modified files for your reference.

Best,
Jose

[createCalendarEventStorePictureRemoval.zip](https://github.com/appnexus/mobile-sdk-ios/files/839850/createCalendarEventStorePictureRemoval.zip)

**Comment by xavierjurado** [comment]
Thanks for the info, much appreciated 👍

**Comment by josecu** [comment]
(Internal use only - [MS-2931](https://jira.corp.appnexus.com/browse/MS-2931))

**Comment by RanfDom** [comment]
@josecu do you have any time set for this upgrade? @xavierjurado did it worked for you? I'm having the same issue :(

**Comment by xavierjurado** [comment]
Yes, we forked the repo and applied the changes to remove all references to `EKEventStore` @RanfDom

**Comment by xavierjurado** [comment]
Any update on the issue @josecu ? Thanks!

**Comment by koenpunt** [comment]
@josecu can you publish the suggested changes on a separate branch maybe? Because now everyone have to fork and make those same changes there..

**Comment by SandorUK** [comment]
Hi guys, have you been able to solve this in any way apart from branching and adding NSCalendarsUsageDescription to plist?

**Comment by ppuviarasu** [comment]
Hi Sandor,

To file an issue or request an enhancement please visit the AppNexus Customer Support Portal (https://support.appnexus.com). This will improve our ability to track these requests. We do not accept GitHub issues.

Thanks,
Punnaghai

**Comment by xavierjurado** [comment]
The issue is already filled here and in your internal Jira @ppuviarasu (https://jira.corp.appnexus.com/browse/MS-2931). Do you have any update to share with us?

**Comment by mbanasiewicz** [comment]
Hey, any updates on this ? @ppuviarasu

**Comment by ppuviarasu** [comment]
This would be removed in the upcoming release...

**Comment by ikovalisko** [comment]
@ppuviarasu that would be really great!

**Comment by ppuviarasu** [comment]
Hey All,

This issue is closed now with the new SDK 4.0.1 release.

**Comment by ppuviarasu** [comment]
Please open a new ticket for any other issues
Thanks everyone for taking the time to improve the SDK
