### ISSUE TITLE
Can't recognize ANBannerAdView in Swift project

### ISSUE THREAD

**Issue by nharbo** [appnexus/mobile-sdk-ios#16]
Hi guys,

I've added the AppNexusSDK via cocoapods, and created a bridgning-header, where I've imported "AppNexusSDK/ANBannerAdView.h" .. If I'm not writing AppNexusSDK/ infront of the .h-file, it won't be recognized.
My issue now is, that my swift file still not recognizes the ANBannerAdView-class..

Any idea why?
I have tried to import the ANBannerAdView like you do normally with swift as well, without any luck.

Thanks.

**Comment by sgallo0692** [comment]
Hi @nharbo,

Have you added the -ObjC linker flag in your build settings? Can you provide the full bridge file you are using?

**Comment by sgallo0692** [comment]
@nharbo can you also provide us with your Podfile?

**Comment by nharbo** [comment]
Hey! Sorry my late reply!
Here's my Podfile:

------ PODFILE START -------

# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'concept-ios' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  #UI
  pod 'SWRevealViewController' #,'2.3.0'
  
  #AdServer SDKs
  pod 'Google-Mobile-Ads-SDK' #, '~> 7.8'
  pod 'AppNexusSDK' #, '2.14'


end

------ PODFILE END -------


In my Bridgning-Header I import this:

#import "AppNexusSDK/ANBannerAdView.h"

And nothing else..
I have to do the AppNexusSDK/ infront of the ANBannerAdView.h to get it to build properly.
But in my swift-viewcontroller, it wont recognize the ANBannerAdView-class. And actually now suddently it gives med this error in the NSTimer+ANCategory.h-file as well:

+ (NSTimer *)an_scheduledTimerWithTimeInterval:(NSTimeInterval)interval
                                         block:(void (^)())block
                                       repeats:(BOOL)repeats
                                          mode:(NSRunLoopMode)mode;

error: Expected a type.


Do you have any ideas about whats going on ? :)¨
Usually when importing Obj-C libs with cocpapods, I don't have to use bridging-headers anymore.. How come I have to with your SDK? :)

Thanks for your time!

**Comment by nharbo** [comment]
![screen shot 2017-05-26 at 14 11 57](https://cloud.githubusercontent.com/assets/11289157/26494090/6961af06-421d-11e7-8117-98633b3e75b0.png)

**Comment by nharbo** [comment]
![screen shot 2017-05-26 at 14 13 47](https://cloud.githubusercontent.com/assets/11289157/26494123/97ac84b2-421d-11e7-880f-33bb26b3ca90.png)

**Comment by nharbo** [comment]
![screen shot 2017-05-26 at 14 17 06](https://cloud.githubusercontent.com/assets/11289157/26494232/16dc364c-421e-11e7-847f-4f91dfba642a.png)

**Comment by nharbo** [comment]
![screen shot 2017-05-26 at 14 17 26](https://cloud.githubusercontent.com/assets/11289157/26494240/1ce9fe20-421e-11e7-90d3-bc2ca3f3dd01.png)

**Comment by nharbo** [comment]
@sgallo0692

**Comment by nharbo** [comment]
@sgallo0692  - any news for this one? Stil haven't found a solution.. :/

**Comment by nharbo** [comment]
@sgallo0692  - any news for this one? Stil haven't found a solution.. :/

**Comment by sgallo0692** [comment]
@nharbo when importing our SDK via cocoapods, you should not need to build any kind of bridging header. The AppNexus SDK should just work when being included via cocoapods. Can you submit a ticket to support.appnexus.com so that we can track this a little more easily and follow up with you quicker? Thanks!

**Comment by AtifNaveed** [comment]
@nharbo you found any solution for this?

**Comment by ppuviarasu** [comment]
Hi All,

While integrating using cocoapods as @sgallo0692 mentioned do not include AppNexusSDK in  bridging headers... 
Also `ANBannerAdView` is part of `AppNexusSDK` hence if you import `AppNexusSDK` that should be fine...

here is a sample of how this is working

```//
//  AppNexusTestAppSwift-Bridging-Header.h
//  AppNexusTestAppSwift
//
//  Copyright © 2017 AppNexus. All rights reserved.
//

#ifndef AppNexusTestAppSwift_Bridging_Header_h
#define AppNexusTestAppSwift_Bridging_Header_h


#endif /* AppNexusTestAppSwift_Bridging_Header_h */
```

```
//
//  ViewController.swift
//  AppNexusTestAppSwift
//
//  Copyright © 2017 AppNexus. All rights reserved.
//

import UIKit
import AppNexusSDK

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        let banner = ANBannerAdView (frame: CGRect(x:0,y:0,width:320,height:50));
        
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


}
```

let me know if this helps

**Comment by Kowshickkarthick** [comment]
Closing this ticket as per comments above.
