### ISSUE TITLE
Feature requests / issue list

### ISSUE THREAD

**Issue by mbanasiewicz** [appnexus/mobile-sdk-ios#19]
Hello! 
First of all thank you for creating this library, we really appreciate it being open source! 
We are using it extensively at Schibsted, however there are some things / feature requests that I would like to list in this issue:

- Would it be possible to make a thin version of this framework that only displays ads in a WKWebView? Current repo has ~557 MB, mostly because of mediation frameworks.
<img width="265" alt="screen shot 2017-06-19 at 11 31 16" src="https://user-images.githubusercontent.com/1093407/27278838-dcc4e0d0-54e2-11e7-88e4-17280e352a6c.PNG">

- Some ads cause scrolling performance to deteriorate if we embed them in UITableView / UICollectionView cells
- Resizing behaviour is a bit cryptic at least to me, could you provide some explanation about how it works ? 
- I know that Carthage is supported, but every time I build AppNexus SDK it also builds KIF
- NSURLConnection header has this comment at the very top ```/*** DEPRECATED: The NSURLConnection class should no longer be used.  NSURLSession is the replacement for NSURLConnection ***/``` I think that `ANAdFetcher` should be rewritten to NSURLSession
- Would it be possible to add nullability markers to Obj-C headers ? At the moment everything is bridged to Swift as explicitly unwrapped optional

If you want me to split this into multiple issues please let me know!

**Comment by sgallo0692** [comment]
Hi @mbanasiewicz!

Thanks for reaching out. Could you please provide these feature requests through our support portal so that they can be properly scoped/triaged by our team? This will also improve our ability to track these requests. 

You can access our portal at support.appnexus.com.

Best,
Steve

**Comment by mbanasiewicz** [comment]
Hi @sgallo0692 👋 
I've submitted the case through support portal
