### ISSUE TITLE
MRAID playVideo command always plays video full screen

### ISSUE THREAD

**Issue by mohammedDehairy** [appnexus/mobile-sdk-ios#20]
I noticed in the code specifically in 
``[ANMRAIDContainerView adShouldPlayVideoWithUri]``
 in response to the playVideo command, it calls
`` [ANMRAIDUtil playVideoWithUri:uri
           fromRootViewController:withCompletionTarget:completionSelector:];``
, then it plays video fullscreen, is this correct ? 

because we have a problem where a video ad starts playing fullscreen once the ad is loaded without the user tapping on it, more over, the app crashes sometimes with this crash log 

``Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x18f9fafe0 __exceptionPreprocess
1  libobjc.A.dylib                0x18e45c538 objc_exception_throw
2  CoreFoundation                 0x18f9faeb4 +[NSException raise:format:]
3  Foundation                     0x190493760 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  UIKit                          0x195da8fd0 -[UIApplication _cachedSystemAnimationFenceCreatingIfNecessary:]
5  UIKit                          0x195e01b0c +[UIWindow _synchronizeDrawingWithPreCommitHandler:]
6  UIKit                          0x195be67a8 -[UIApplication _setStatusBarHidden:animationParameters:changeApplicationFlag:]
7  UIKit                          0x195b33710 -[UIApplication _updateCurrentStatusBarViewControllerAppearance]
8  UIKit                          0x195ba1a80 -[UIViewController setNeedsStatusBarAppearanceUpdate]
9  UIKit                          0x195c266dc -[UIViewController _setPresentedStatusBarViewController:]
10 UIKit                          0x195ea163c -[UIViewController _dismissViewControllerWithAnimationController:interactionController:completion:]
11 UIKit                          0x195c56848 -[UIViewController _dismissViewControllerWithTransition:from:completion:]
12 UIKit                          0x195bfe6dc -[UIViewController dismissViewControllerWithTransition:completion:]
13 UIKit                          0x195bfe4bc -[UIViewController dismissViewControllerWithTransition:completion:]
14 UIKit                          0x195ea07e4 -[UIViewController _performCoordinatedPresentOrDismiss:animated:]
15 UIKit                          0x195bfe230 -[UIViewController dismissViewControllerAnimated:completion:]
16 AVKit                          0x19d29ac50 -[AVPlayerViewController _transitionFromFullScreenViewControllerAnimated:completionHandler:]
17 AVKit                          0x19d29d5f8 -[AVPlayerViewController(AVPlayerViewController_WebKitOnly) exitFullScreenAnimated:completionHandler:]
18 WebCore                        0x1955c9550 WebCore::WebVideoFullscreenInterfaceAVKit::exitFullscreen(WebCore::IntRect const&)
19 WebCore                        0x1955c7de8 WebCore::WebVideoFullscreenInterfaceAVKit::watchdogTimerFired()
20 WebCore                        0x194576e00 WebCore::ThreadTimers::sharedTimerFiredInternal()
21 WebCore                        0x194576d40 WebCore::timerFired(__CFRunLoopTimer*, void*)
22 CoreFoundation                 0x18f9a9aa4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
23 CoreFoundation                 0x18f9a97a8 __CFRunLoopDoTimer
24 CoreFoundation                 0x18f9a9068 __CFRunLoopDoTimers
25 CoreFoundation                 0x18f9a6c8c __CFRunLoopRun
26 CoreFoundation                 0x18f8d6da4 CFRunLoopRunSpecific
27 WebCore                        0x1945a8d3c RunWebThread(void*)
28 libsystem_pthread.dylib        0x18eabd68c _pthread_body
29 libsystem_pthread.dylib        0x18eabd59c _pthread_body
30 libsystem_pthread.dylib        0x18eabacb4 thread_start``

**Comment by Kowshickkarthick** [comment]
We will track this request via the support process & JIRA. Let us know if you need anything else.
