### ISSUE TITLE
Getting banner's size when creating an "ANBannerAdView" with several adSizes

### ISSUE THREAD

**Issue by maurovz** [appnexus/mobile-sdk-ios#21]
Hi, I'm just starting with AppNexus and the AppNexus iOS SDK. I'm creating a banner ad using something similar to:

```
let ad = ANBannerAdView(frame: frame, memberId: id, inventoryCode: "code")
ad?.adSizes = [size1, size2, size3, size4]
ad?.loadAd()
```

I want to adjust the height of the view depending on the banner's height. I tried using `ad?.adSize` but it always returns the size of the first element in the array. In this case `size1`. 

For this reason, I'm unable to adjust the height of the container view when the height is different than `size1` and I end up with empty spaces. How can I get the size of the actual banner that's being used?

<img width="227" alt="screen shot 2017-11-15 at 15 45 32" src="https://user-images.githubusercontent.com/1994477/32862799-ef7e1244-ca1e-11e7-8195-af06bb64bb1c.png">
<img width="227" alt="screen shot 2017-11-15 at 15 56 24" src="https://user-images.githubusercontent.com/1994477/32862800-ef9aa6d4-ca1e-11e7-813f-8996e819b8d7.png">

**Comment by herrernst** [comment]
I had the same problem, solution is to expose a `contentView` property of `ANBannerAdView` and get its height when the ad is loaded: https://wiki.appnexus.com/display/sdk/Resize+the+Banner+Ad+View+to+the+Size+of+the+Winning+Creative#ResizetheBannerAdViewtotheSizeoftheWinningCreative-iOS
