### ISSUE TITLE
iPhone X - WKWebView scrollView gets undesired insets

### ISSUE THREAD

**Issue by salling** [appnexus/mobile-sdk-ios#23]
We have a scenario where ANBannerAdView is inside a scroll view of ours, where we handle safe area insets etc for iPhone X. Such being the case, things break when the scroll view inside the web view contained inside ANBannerAdView gets the iPhone X automatic insets treatment. (see attached screen shot; the ad content is scrolled within the ad view itself and is therefore partially obscured).

Doing this on the web view fixes things (but since we don't have clean access to this view, I'm requesting that this is fixed inside your SDK):
webView.scrollView.contentInsetAdjustmentBehavior = .never

<img width="407" alt="screen shot 2018-02-20 at 16 02 33" src="https://user-images.githubusercontent.com/1453580/36431442-e68ff460-1657-11e8-8ea0-93afdc7fd23b.png">

<img width="1147" alt="screen shot 2018-02-20 at 16 02 08" src="https://user-images.githubusercontent.com/1453580/36431438-e255044e-1657-11e8-94a2-15993782c955.png">

**Comment by Kowshickkarthick** [comment]
This issue has been fixed in v4.4 release
https://github.com/appnexus/mobile-sdk-ios/releases/tag/4.4
