### ISSUE TITLE
AN Localizations overriding parent app localizations

### ISSUE THREAD

**Issue by amitjainpdx** [appnexus/mobile-sdk-ios#25]
Pods/AppNexusSDK/sdk/Resources/Base.lproj/Localizable.strings

overwrites the parent app localizations.

Please move AN Localization string file inside AN bundle and use NSLocalizedStringFromTableInBundle instead of NSLocalizedString for the "OK" text.

**Comment by asharmaa** [comment]
This has been fixed and release as part of AppNexus iOS SDK version 4.4.2 - 
https://github.com/appnexus/mobile-sdk-ios/releases/tag/4.4.2
