### ISSUE TITLE
Application crashes when trying to Download a banner with null width or height

### ISSUE THREAD

**Issue by rokridi** [appnexus/mobile-sdk-ios#36]
**_Version: 4.11.1_**

**Issue:**

When I try to instantiate `ANBannerAdView` with a width or height equal to 0 then the application crashes.
I investigated through source code and found out that the `ANBannerAdView` logs an error message but the execution continues.

if you look at `ANBannerAdView` 's `-setAdSizes:` you will find out that the method returns if the size is not valid. However, the process of building the Network request continues and then the Appnexus library crashes  in `ANBannerAdView` 's `-internalDelegateUniversalTagSizeParameters` and to be specific it is the following line that causes the crash `[delegateReturnDictionary setObject:self.adSizes                             forKey:ANInternalDelegateTagKeySizes];`.
That is because `self.adSizes` is nil.

**Suggestion:**

When trying to initialise a `ANBannerAdView` then stop the whole process and return an error via delegate methods or a reference to a NSError object.

**Comment by medslt** [comment]
Have the same problem here! :(

**Comment by winterized** [comment]
Same here :(

**Comment by shanshan33** [comment]
Same here. Even I set default size for adSize, crash still :(

**Comment by asharmaa** [comment]
This issue is fixed and released as part of AppNexus iOS SDK Version 5.0
