### ISSUE TITLE
Application freezes when download native ad

### ISSUE THREAD

**Issue by shanshan33** [appnexus/mobile-sdk-ios#37]
Hello, 

We've experience a freeze issues when download native ad in a tableview, we have produce in a bad network connection (Edge)
After the investigate, we find out that in the ANNativeAdRequest, In method  `setImageForImageURL:onObject:forKeyPath:` you have created an loadImageData operation to download image, then, you've add this operations in mainQueue. 

Then this method has been use in `universalAdFetcher: didFinishRequestWithResponse:`to download mainImage and iconImage for Native ad, with completion of an other operation `finish`. 
So the operations are all in `[NSOperationQueue mainQueue]`, the finish block depends on others, so it will executed once load image data operations finish, and it make the freezes.

Here is our proposition to solve this problem: 
Create another queue for download image data, we've run some test with this solution, and it fix the problems. 

Please fix it soon, it absolutely has huge impact for the user experience of our application. 

Thank you.

**Comment by Kowshickkarthick** [comment]
The issue has been fixed in v5.0.1
The images are now downloaded in a background thread
