### ISSUE TITLE
Potential risk to block forever in dispatch_semaphore_wait() for a released semaphor ??

### ISSUE THREAD

**Issue by shanshan33** [appnexus/mobile-sdk-ios#38]
Hello,

Thank you for the latest update.
At the mean time, I have a question about your last modification in ANNativeAdRequest.

In the method setImageInBackgroundForImageURL: onObject:forKeyPath: you will  release de semaphore after finish download image (mainImage ou iconImage).

In the method universalAdFetcher: didFinishRequestWithResponse:

You have download images in background queue, if semaphore is defined, call dispatch_semaphore_wait(semaphor, DISPATCH_TIME_FOREVER) to wait for this background task.
But what if semaphoreIconImage is released before semaphoreMainImage ?

Does it has risk that semaphoreIconImage finish early and it could be released, so the code will block in
dispatch_semaphore_wait(semaphoreIconImage, DISPATCH_TIME_FOREVER);?

**Comment by Kowshickkarthick** [comment]
Hi @shanshan33 ,

These are the various states  `semaphoreIconImage` can be,
nil - initial state.
0   - when the background download is in progress. (dispatch_semaphore_create(0);)
1   - when the download has completed. (dispatch_semaphore_signal(semaphore);)

Irrespective of the order in which the download completes,
`dispatch_semaphore_wait(semaphoreIconImage, DISPATCH_TIME_FOREVER); `
Decrements the value of semaphoreIconImage. If the resulting value is less than zero, this function waits for a signal to occur before returning.

In cases where the download has completed before this line is executed the value of semaphoreIconImage is 1, decrementing which the resulting value is 0.
And there is no wait.

We have tested for this scenario and there is no wait.

**Comment by Kowshickkarthick** [comment]
Hi @shanshan33  

Closing this ticket for now.
If you feel you need further assistance on this, please reach out through our support portal https://support.appnexus.com. 

Thanks,
Kowshick S
