### ISSUE TITLE
Initialize ANBannerAdView with memberId and inventoryCode throws error

### ISSUE THREAD

**Issue by NRiebesel** [appnexus/mobile-sdk-ios#39]
Hi there,

when I'm trying to initialize a ANBannerAdView with memberId and inventoryCode I always get an error:
**'No known class method for selector 'initWithFrame:memberId:inventoryCode:'**
This may be syntax related and since Im not very deep into iOS Development it is likely.

This is the line in my code:
`ANBannerAdView *banner = [ANBannerAdView initWithFrame:(CGRect)rect memberId:(NSInteger)memberId inventoryCode:(NSString *)inventoryCode];`

memberId is 4-digit Integer and the inventoryCode a String of the placement code I want to request. I followed the Mobile SDK documentation so far it works with the documentation example:
`ANBannerAdView *banner = [ANBannerAdView adViewWithFrame:rect placementId:@"12345679"];` but not with memberId+inventoryCode.

I'd be grateful if you could have a look on this and could give me some support.

Thanks in advance!

PS. I'm using the version 5.1.1 of the SDK with cocoapods.

**Comment by Kowshickkarthick** [comment]
Hi @NRiebesel 

You need to use:
```
 ANBannerAdView *banner = [[ANBannerAdView alloc] initWithFrame:rect memberId:MEMBER_ID inventoryCode:@"INVENTORYCODE" adSize:size];
```

Here is a Simple View Controller displaying a Banner using member_id and inventory code:
Please note: This is just a very simple usage of the Banner API's

```

#import "SimpleViewController.h"
#import "ANBannerAdView.h"



@interface SimpleViewController () <ANBannerAdViewDelegate>

@property (nonatomic, readwrite, strong) ANBannerAdView *banner;


@end

@implementation SimpleViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
    
    int adWidth  = 300;
    int adHeight = 250;
    
    // We want to center our ad on the screen.
    CGRect screenRect = [[UIScreen mainScreen] bounds];
    CGFloat originX = (screenRect.size.width / 2) - (adWidth / 2);
    CGFloat originY = (screenRect.size.height / 2) - (adHeight / 2);
    
    // Needed for when we create our ad view.
    CGRect rect = CGRectMake(originX, originY, adWidth, adHeight);
    CGSize size = CGSizeMake(adWidth, adHeight);
    
    // Make a banner ad view.
    ANBannerAdView *banner = [[ANBannerAdView alloc] initWithFrame:rect memberId:958 inventoryCode:@"universalPlacement" adSize:size];
    banner.rootViewController = self;
    banner.delegate = self;
    [self.view addSubview:banner];
    
    // Load an ad.
    [banner loadAd];
    self.banner = banner;
}

- (void)adDidReceiveAd:(id)ad {
    NSLog(@"Ad did receive ad");
}


- (void)adDidClose:(id)ad {
    NSLog(@"Ad did close");
}

- (void)adWasClicked:(id)ad {
    NSLog(@"Ad was clicked");
}

- (void)ad:(id)ad requestFailedWithError:(NSError *)error {
    NSLog(@"Ad failed to load: %@", error);
}

- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

@end


```

**Comment by NRiebesel** [comment]
Great! It works now, thanks a lot!!
