### ISSUE TITLE
How to identifier different type of Google advertising without ANAdAdapterNativeAdMobAdType

### ISSUE THREAD

**Issue by shanshan33** [appnexus/mobile-sdk-ios#41]
Hello AppNexus Team, 

In my application iOS, I am using Google as mediation. when I got the response of ANNativeAdResponse, I used to check networkCode to identifier the AdMob (Google) type. 

Actually, I could received two type of Google Advertsing, as AdMobContent and AdMobInstall, I used to use ANAdAdapterNativeAdMobAdType to separate them as following code :

`if let rawType = elements[kANAdAdapterNativeAdMobAdKey] as? Int, let type = ANAdAdapterNativeAdMobAdType(rawValue: rawType) {
switch type {
        case .content: 
        case .install: 
}`

From your last update, ANAdAdapterNativeAdMobAdType is not available anymore. 
How could I identifier different type of google advertising ?

Thank you for your attention.

**Comment by Kowshickkarthick** [comment]
Hi @shanshan33,

Google has combined both `GADNativeAppInstallAd` and `GADNativeContentAd` into one new type: `GADUnifiedNativeAd`. And has deprecated the old ones in favor of the new.

To keep up with Google's changes we have updated our mediation adapter code to be based on `GADUnifiedNativeAd` in our last release(SDK v5.1). And it is a breaking change.

You no longer need to create two different views based on the response type. Its just one `GADUnifiedNativeAdView`.

Please modify your implementation based on the instruction in below pages:
https://wiki.appnexus.com/display/sdk/Mediate+with+iOS
https://developers.google.com/admob/ios/native/start
https://developers.google.com/admob/ios/native/advanced

Thanks,
Kowshick S

**Comment by shanshan33** [comment]
Hello Kowshick, 

Thank you for your response, we are aware that it become one type GADUnifiedNativeAdView. 

But actually, in the production, we have a view with design specific for appInstall ( appStore Icon, Telecharge Icon, Stars Rating View.. etc) and content as same design as native. 

I am wondering, if we need to keep the two design ( asking from product), could we identifier with this ?

`open var rating: ANNativeAdStarRating! ` 

for example, we check if rating exist, or rating > 0, we know it's reserved for an app install ad ? 

Thank you for your attention.

**Comment by Kowshickkarthick** [comment]
HI @shanshan33 ,

`ANNativeAdStarRating` value is always non-nil for Google Mediation Case and it defaults to `0` if `GADUnifiedNativeAd.starRating == nil`.

With OpenRTB Native Spec 1.2 star rating has been generified.
If google has adopted it, then star rating will be available for non-app install ads as well.
Instead you can rely on `nativeAd.store` for future proofing

I would recommend doing something like below:

    func adRequest(_ request: ANNativeAdRequest!, didReceive response: ANNativeAdResponse!) {
        if(response.networkCode == ANNativeAdNetworkCode.adMob){
            // Google Native Ad response handling
            let nativeAd: GADUnifiedNativeAd! = response?.customElements[kANNativeElementObject] as? GADUnifiedNativeAd
            if(nativeAd.store == nil){
                 //nativeAd.starRating == nil //also can check for starRating == nil the same way
                 print("AdMob Content Ad")
            }else{
                print("AdMob AppInstall Ad")
            }
        }else{
            // AppNexus and other native ad response handling
            print("Appnexus")
        }
    }

**Comment by shanshan33** [comment]
Thank you for your reply, it's being very helpful.
