### ISSUE TITLE
ANMediationContainerView doesn't resize when use SmartMediation

### ISSUE THREAD

**Issue by shanshan33** [appnexus/mobile-sdk-ios#42]
Hello AppNexus Team, 

We've update to your lastest version 5.1.1 to support Smart Mediation.
To get the format Parallax and Video Smart: 
we have sent request as following code: 

`let banner = ANBannerAdView(frame: frame, memberId: memberID, inventoryCode: inventoryCode, adSize: CGSize(width: 320, height: 180))`

we have response. and our ANBannerAdView has been resize to fit the tableview, but we have a margin white around ANMediationContainerView,
We've already use the following code,  `banner?.shouldResizeAdToFitContainer = true`
but truns out that ANMediationContainerView doesn't fit the size of ANBannerAdView. 

![screenshot 2019-02-22 at 18 06 52](https://user-images.githubusercontent.com/1665445/53258908-0ebde680-36ce-11e9-8169-e91fe93dbda6.png)

Do you have idea about it ?
Thank you for your attention.

**Comment by Kowshickkarthick** [comment]
Hi @shanshan33 ,

Not all properties that are applied on ANBannerAdView are transitively applied for Mediation use cases.
Some times the mediation adapter in question will not have an equivalent functionality as that of AppNexus SDK and it won't be possible to support that functionality. We do it on a case by case basis.

Although in this particular case it looks like, its possible that we could support it. There is a similar request on Android which we are currently working on.

Can you reach out to AppNexus support via your support person or through support.appnexus.com
We can prioritize this feature and work on this internally.

Thanks and BR,
Kowshick S

**Comment by Kowshickkarthick** [comment]
HI @shanshan33 ,

This issue has been fixed in v5.3 of SDK.
