### ISSUE TITLE
iOS Deprecated UIWebView API usage warning

### ISSUE THREAD

**Issue by PatrickDotStar** [appnexus/mobile-sdk-ios#46]
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

Apple will, probably with the release of iOS 13, no longer accept builds that make use of deprecated UIWebView in favor of using WKWebView.
There are still some UIWebView usages within AppNexus for eg in `ANANJAMImplementation.m`

**Comment by ppuviarasu** [comment]
Hi @PatrickDotStar,
thanks for raising the issue. We are looking into this and you will find an update in the next release.

**Comment by asharmaa** [comment]
The issue has been fixed in v6.1. SDKv6.1 is the official release for iOS 13 support.
Thank you
