### ISSUE TITLE
Interstitial ad crashes the whole application if orientation not supported

### ISSUE THREAD

**Issue by mrTuomoK** [appnexus/mobile-sdk-ios#47]
I'm testing interstitial ads in my app and it keeps crashing when the ad tries to set the orientation of the screen (I guess). The app is locked in portrait mode. I'm using the new 6.0 SDK and running the app on iOS 12.4 (iPhone XR). Even though the ad would like to change the orientation to landscape or whatever it shouldn't crash if it's disallowed.

Here's some error log...

`
2019-09-13 08:23:23.065857+0300 xxx[7142:63370] *** Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [ANInterstitialAdViewController shouldAutorotate] is returning YES'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001129288db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000110aafac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000112928735 +[NSException raise:format:] + 197
	3   UIKitCore                           0x000000011f996303 -[UIViewController __supportedInterfaceOrientations] + 921
	4   UIKitCore                           0x000000011f996859 -[UIViewController __withSupportedInterfaceOrientation:apply:] + 45
	5   UIKitCore                           0x000000011f9971dd -[UIViewController _updateLastKnownInterfaceOrientationOnPresentionStack:] + 223
	6   UIKitCore                           0x000000011ffbc405 -[UIWindow _setRotatableViewOrientation:updateStatusBar:duration:force:] + 165
	7   UIKitCore                           0x000000011f89f04a -[_UIFullscreenPresentationController _placeCounterRotationViewWithView:inWindow:fromOrientation:toOrientation:force:] + 560
	8   UIKitCore                           0x000000011f89ed5d -[_UIFullscreenPresentationController _adjustOrientationIfNecessaryInWindow:forViewController:preservingViewController:] + 887
	9   UIKitCore                           0x000000011f894a0e -[UIPresentationController _presentWithAnimationController:interactionController:target:didEndSelector:] + 953
	10  UIKitCore                           0x000000011f98991b -[UIViewController _presentViewController:modalSourceViewController:presentationController:animationController:interactionController:completion:] + 1485
	11  UIKitCore                           0x000000011f98b516 -[UIViewController _presentViewController:withAnimationController:completion:] + 4608
	12  UIKitCore                           0x000000011f98ddd7 __63-[UIViewController _presentViewController:animated:completion:]_block_invoke + 98
	13  UIKitCore                           0x000000011f98e2ef -[UIViewController _performCoordinatedPresentOrDismiss:animated:] + 511
	14  UIKitCore                           0x000000011f98dd3e -[UIViewController _presentViewController:animated:completion:] + 172
	15  UIKitCore                           0x000000011f98df9c -[UIViewController presentViewController:animated:completion:] + 150
	16  almaRap                             0x000000010d862e14 -[ANInterstitialAd displayAdFromViewController:autoDismissDelay:] + 2033
	17  almaRap                             0x000000010d84308b $s7almaRap28InterstitialAdViewControllerC012adDidReceiveD0yyypFTo + 155
	18  almaRap                             0x000000010d850e08 -[ANAdView adDidReceiveAd:] + 137
	19  almaRap                             0x000000010d863172 -[ANInterstitialAd universalAdFetcher:didFinishRequestWithResponse:] + 480
	20  almaRap                             0x000000010d87d6a5 -[ANUniversalAdFetcher processFinalResponse:] + 170
	21  almaRap                             0x000000010d87ed71 -[ANUniversalAdFetcher didCompleteFirstLoadFromWebViewController:] + 501
	22  almaRap                             0x000000010d8698dc __66-[ANMRAIDContainerView didCompleteFirstLoadFromWebViewController:]_block_invoke + 297
	23  libdispatch.dylib                   0x00000001151c1d02 _dispatch_client_callout + 8
	24  libdispatch.dylib                   0x00000001151c46be _dispatch_continuation_pop + 440
	25  libdispatch.dylib                   0x00000001151d4997 _dispatch_source_invoke + 2072
	26  libdispatch.dylib                   0x00000001151cd8e3 _dispatch_main_queue_callback_4CF + 911
	27  CoreFoundation                      0x000000011288fa79 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	28  CoreFoundation                      0x000000011288a126 __CFRunLoopRun + 2310
	29  CoreFoundation                      0x00000001128894d2 CFRunLoopRunSpecific + 626
	30  GraphicsServices                    0x00000001171fa2fe GSEventRunModal + 65
	31  UIKitCore                           0x000000011ff7afc2 UIApplicationMain + 140
	32  almaRap                             0x000000010d83d51b main + 80
	33  libdyld.dylib                       0x000000011522f541 start + 1
	34  ???                                 0x0000000000000001 0x0 + 1

`

**Comment by asharmaa** [comment]
Issue is not getting replicated with the change suggested above.
Please share the Placement/Creative used for this issue
It would be nice if you can share the step to produce or a sample App.

**Comment by mrTuomoK** [comment]
Ok here's the code I test it with. Created a new iOS swift project and then use the following code in the main viewController

`
import AppNexusSDK
import UIKit

class ViewController: UIViewController {
    
    var inter:ANInterstitialAd?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        inter = ANInterstitialAd.init(placementId: "15012792")
        inter?.delegate = self
        inter?.load()
    }

}

extension ViewController: ANInterstitialAdDelegate {
    func adDidReceiveAd(_ ad: Any) {
        NSLog("adDidReceiveAd INTERSTITIAL")
        inter?.display(from: self)
    }
}
`

With placementId 15012792 it will sometimes crash due to this orientation error (there's 3 different test-ads served with this id and one of them is crashing) and the error message is:

 *** Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [ANInterstitialAdViewController shouldAutorotate] is returning YES'

**Comment by asharmaa** [comment]
Thanks the steps. We are able to reproduce the issue at our end.
We will have this fixed in our next release.

**Comment by asharmaa** [comment]
The crash is fixed and released as part of AppNexus iOS SDK Version 6.1
Thank you
