### ISSUE TITLE
Crash [ANBrowserViewController loadAndPresentStoreControllerWithiTunesId:] sur IOS 13.0

### ISSUE THREAD

**Issue by shanshan33** [appnexus/mobile-sdk-ios#48]
Hello AppNexus team, 

We have a crash 100% reproduced when we click sur advertising format interstitiel or native, if only the redirection url concern App Store in iOS 13.0. 

<img width="753" alt="Capture d’écran 2019-10-28 à 11 31 33" src="https://user-images.githubusercontent.com/1665445/67671601-8a1b1a80-f976-11e9-9783-aefb1a8a765a.png">

After investigation from our side, the problem looks comes from subclassing of **SKStoreProductViewController**
In apple's documentation, they mentioned that **The SKStoreProductViewController class does not support subclassing or embedding, and must be used as-is. If you compile with the iOS 13 SDK, attempting to instantiate a subclass of SKStoreProductViewController results in a runtime exception.** 

Here is the documentation and our crash log. https://developer.apple.com/documentation/storekit/skstoreproductviewcontroller

More information about the crash, we have 300 since last week, 100% in iOS 13.0. We are using version 6.1. 

Please fix it soon, thank you in advance. Have a good day !

[fr.leboncoin.leboncoin_issue_crash_5a3c1e1821b14db58a982ba45288c051_DNE_1_v2.txt](https://github.com/appnexus/mobile-sdk-ios/files/3778275/fr.leboncoin.leboncoin_issue_crash_5a3c1e1821b14db58a982ba45288c051_DNE_1_v2.txt)

**Comment by ppuviarasu** [comment]
Thank you for informing us. We will provide a fix for the same as soon as possible.

**Comment by ppuviarasu** [comment]
We have resolved this and provided a fix in v6.1.2. Do download the latest.
