### ISSUE TITLE
iOS 14: advertisingIdentifier

### ISSUE THREAD

**Issue by MaartenZonneveld** [appnexus/mobile-sdk-ios#52]
The SDK uses the `advertisingIdentifier` property here: https://github.com/appnexus/mobile-sdk-ios/blob/f87a0f064ab25be80b7482df3c0f849a2a9e9201/sdk/sourcefiles/internal/ANGlobal.m#L85.

From iOS 14, this will no longer work without first asking the user's permission. Are there any updates planned to support this new behaviour in iOS 14?

**Comment by ppuviarasu** [comment]
With the recent announcement from Apple about delaying the requirement to obtain permission to track users starting early next year

https://developer.apple.com/news/?id=hx9s63c5&1599152522

we will wait for a more clear directive from Apple to make any further changes.

**Comment by srijithnair** [comment]
+1 on @ppuviarasu's comment. We are working with our product team to address and support iOS 14 related changes. Please stay tuned for updates via our regular release channels regarding this.
