### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by ivanlisovyi** [appnexus/mobile-sdk-ios#60]
Do you have plans to add support for the Swift Package Manager to the SDK anytime soon? 

There is already an experimental support for SPM implemented in scope of #55.

**Comment by srijithnair** [comment]
Yes, we do! We are currently scoping this and identifying external dependencies (e.g., OMSDK). Please feel free to close this ticket as we are already planning for/tracking this internally.

**Comment by ivanlisovyi** [comment]
@srijithnair This is a very good news. Do you have any ETA to share with us? :)

**Comment by marcin-bo** [comment]
Hi,

Swift Package Manager support would be very appreciated.

**Comment by clausjoergensen** [comment]
Looks like this was added in https://github.com/appnexus/mobile-sdk-ios/releases/tag/7.15 !

**Comment by asharmaa** [comment]
Hello @ivanlisovyi,

Swift package manager support is added, please have a look at SDK [version 7.15.1](https://github.com/appnexus/mobile-sdk-ios/releases/tag/7.15.1)


Thanks
Abhishek
