### ISSUE TITLE
Update Google-Mobile-Ads-SDK dependency

### ISSUE THREAD

**Issue by miquelalvarado** [appnexus/mobile-sdk-ios#63]
Hi,

We need to use the `GoogleAdapter` subspec but we are having some conflicts while trying to install the dependency. The error is: 

> Can't merge user_target_xcconfig for pod targets: ["Foo", "Google-Mobile-Ads-SDK"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.

This seems to be caused by a conflict between the `Google-Mobile-Ads-SDK` library which defines in its Podspec:
```ruby
"user_target_xcconfig": {
    "EXCLUDED_ARCHS[sdk=iphonesimulator*]": "i386"
}
```
This seems to be fixed in the version `8.2.0.1` (you can see their release notes [here](https://developers.google.com/admob/ios/rel-notes)) so we would need to update the dependency to -at least- that version.

**Comment by miquelalvarado** [comment]
@asharmaa Sorry to ping you. Is there by any chance any possibility for this to be done anytime soon?

**Comment by Kowshickkarthick** [comment]
Hi @miquelalvarado ,

We tried updating our `GoogleAdapter` to use v8.2.0.1 of `Google-Mobile-Ads-SDK` but faced some issues in PodSpec lint.  
We will not be able to update to v8.2 of Google SDK anytime soon untill we fix our CocoaPods lint  issues. While pushing to Trunk, CocoaPods will perform a lint under the hood. The push will be aborted on lint error.

As an alternative till we fix this, I would recommend to integrate `GoogleAdpater` form source code and include v8.2.0.1 of Google SDK by yourself in the app.
Our adapter code is compatible with 8.2.0.1 of Google SDK.

**Comment by miquelalvarado** [comment]
Hi @Kowshickkarthick,

Even though it won't be anytime soon, can you have an estimation on how much it can take for you to fix the PodSpec lint issue? Is it in your backlog, do you think it could be done during this quarter, for instance?

**Comment by Kowshickkarthick** [comment]
HI @miquelalvarado ,
Yes this is in our backlog.
We have identified the root cause for this issue and are expecting to fix it in our May(best case)/June(worst case) release.

**Comment by miquelalvarado** [comment]
Hi @Kowshickkarthick,
Just wanted to ask for an update. Is the `GoogleAdapter` going to be updated during this month?

Thanks

**Comment by miquelalvarado** [comment]
Ping @Kowshickkarthick

**Comment by Kowshickkarthick** [comment]
HI @miquelalvarado  
Yes, we are updating GoogleAdapter to v8.5.0 as a part of our June release. ETA June 21-25.

**Comment by miquelalvarado** [comment]
Closing the issue as I've seen version 7.15 updates the dependency. Thanks!
