### ISSUE TITLE
ANMultiAdRequest: could not parse valid tag in request

### ISSUE THREAD

**Issue by marcin-bo** [appnexus/mobile-sdk-ios#64]
Hi,

Our app has itegration with your SDK. We use `ANNativeAdRequest` to get native ads. And it works correctly (althout there are some memory leaks - I will report it in a separate issue).

Now, we want to avoid native ads duplication and we're trying to use `ANMultiAdRequest`.

But after integrating it, we get the following errors (the log from SDK debug mode and printed error from ANMultiAdRequest delegate):

```
2021-04-18 01:18:20.783102+0200 AppName  APPNEXUS DEBUG  +[ANUniversalTagAdServerResponse generateTagsFromResponseData:] -- jsonResponse={
    error = "Could not parse valid tag in request";
}
2021-04-18 01:18:20.783181+0200 AppName APPNEXUS ERROR  +[ANUniversalTagAdServerResponse generateTagsFromResponseData:] -- FAILED to find an array of tags in UT Reponse data.
(lldb) po error
Error Domain=com.appnexus.sdk Code=2 "multi_ad_request_failed UT Response FAILED to return any ad objects." UserInfo={NSLocalizedDescription=multi_ad_request_failed UT Response FAILED to return any ad objects.}
MultiAdRequest failed with error: Error Domain=com.appnexus.sdk Code=2 "multi_ad_request_failed UT Response FAILED to return any ad objects." UserInfo={NSLocalizedDescription=multi_ad_request_failed UT Response FAILED to return any ad objects.}
```

We have no idea what `tag` and how to fix it. Could you help us with that?

**Comment by marcin-bo** [comment]
The implementation is done on latest SDK (7.11), according to the example: https://github.com/appnexus/mobile-sdk-ios/blob/master/examples/Swift/SimpleIntegration/SimpleIntegrationSwift/MultiAdRequest/MultiAdViewController.swift

**Comment by Kowshickkarthick** [comment]
Hi,

Can you attach logs for some more timeframe(say for a 5 min app session when you see this issue) where we can see https req/response and processing.

Just by looking at the logs you have posted here, I can say there was no ads array present in the response from our backend. This is normal, we donot expect an ad to be served back all the time. 


Thanks and BR,
Kowshick S

**Comment by marcin-bo** [comment]
Hi,

Here's the console log that contains AppNexus SDK logs:
[console-logs-appnexus-2.txt](https://github.com/appnexus/mobile-sdk-ios/files/6285037/console-logs-appnexus-2.txt)

**Comment by Kowshickkarthick** [comment]
HI @marcin-bo ,

I can see you are using member_id=`10094` which is SDK test member.
Can you use your Apps member_id??
I can see it is `11716` but you should be able to confirm your member id  with you ad-ops team.

**Comment by marcin-bo** [comment]
Thanks, it works!
