### ISSUE TITLE
Cannot open App Store when tapping an ad

### ISSUE THREAD

**Issue by shahzadmajeed** [appnexus/mobile-sdk-ios#7]
Hi I have following standard code which doesn't open app store when I tap an ad which says "Install App". 

banner.opensInNativeBrowser = YES;
banner.autoRefreshInterval = 60;
banner.alignment = ANBannerViewAdAlignmentCenter;
banner.transitionType = ANBannerViewAdTransitionTypeFade;
banner.transitionDirection = ANBannerViewAdTransitionDirectionUp;
banner.transitionDuration = 0.3;
[banner loadAd];

Any suggestion why ?

FYI: I have tried it with `banner.opensInNativeBrowser = NO;` also

**Comment by josecu** [comment]
Could you enable full logging in `ANLogManager` and provide the logs if you’re still able to replicate the issue? Steps for replication would be useful as well. From a high level, app links sometimes don’t work if the app is not available in a given geography, but I don’t know if that does or doesn’t apply to your specific scenario.

**Comment by shahzadmajeed** [comment]
Sure, I will try to replicate that with logging enabled. But I just checked that I didn't integrate the mediation banner adopter for Amazon. Do you think its the reason that the banner showing Amazon ad `Install App` wasn't taking to app store (sorry I forgot to mention that the Install App ad was from Amazon network for AppNexus sdk).

**Comment by josecu** [comment]
I don’t have enough information to know - I don’t know how to explain why you saw an Amazon ad while not integrating the Amazon mediation adapter without an example or logs.
