### ISSUE TITLE
GoogleAdapter support through SPM

### ISSUE THREAD

**Issue by miquelalvarado** [appnexus/mobile-sdk-ios#75]
Hi,

Currently the mobile-sdk-ios is giving support to its installation through SwiftPM but only to its main spec. Could you give also support to GoogleAdapter subspec as well?

Thanks!

**Comment by Daniel-Berger** [comment]
I don't believe that is possible give that Google's AdMob SDK does not support Swift Package Manager ([reference](https://swiftpackageindex.com/search?query=admob)).
