### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by ikovalisko** [appnexus/mobile-sdk-ios#8]
Hi!
I see you are doing a manual release and distribution. This also means that SDK users have to integrate the SDK manually into the project.

Have you considered added CocoaPods support? It's very popular now and simplifies integration. I have noticed you are using external dependencies for other ads providers. This can also be handled by CocoaPods as most of the ads services already support it.

Would like to hear your thoughts.

**Comment by josecu** [comment]
Hi Ivan,
We already offer Cocoapods support. Here is how you would integrate it.

```
platform :ios, '6.0'
 
target 'SimpleBanner' do
  pod 'AppNexusSDK'
end
```

Please see here on including mediation adapters & libraries using Cocoapods:

https://wiki.appnexus.com/display/sdk/Mediate+with+iOS#MediatewithiOS-Prerequisites

Best,
Jose

**Comment by ikovalisko** [comment]
Thanks a lot. I haven't noticed this on wiki, but expected to see in Github's readme.
