### ISSUE TITLE
BuildANSDKCocoaTouchFramework.sh fails

### ISSUE THREAD

**Issue by audungk** [appnexus/mobile-sdk-ios#9]
> The following build commands failed:
> 	CopyPlistFile out/AppNexusSDK.framework/SDKIntegrationKeys.plist AppNexusSDK/SDKIntegrationKeys.plist
> (1 failure)

**Comment by josecu** [comment]
Thanks for reaching out, the fix will be in our next release. In the meantime, you can fix the issue by:
 
1. Opening ANSDK.xcodeproj in the BinaryProjects folder and removing SDKIntegrationKeys.plist as shown in this screenshot:

<img width="1440" alt="screen shot 2016-11-04 at 1 48 05 pm" src="https://cloud.githubusercontent.com/assets/6942011/20016349/6feeeb2c-a295-11e6-8d8e-bff3bfe9919b.png">

2. (Only if using Xcode 8.1) creating an empty property list and adding it to the ANSDKResources.bundle as shown in these screenshots:

<img width="1439" alt="screen shot 2016-11-04 at 1 53 30 pm" src="https://cloud.githubusercontent.com/assets/6942011/20016512/2415627a-a296-11e6-9746-1492c2264973.png">

<img width="1440" alt="screen shot 2016-11-04 at 1 51 45 pm" src="https://cloud.githubusercontent.com/assets/6942011/20016465/f147e912-a295-11e6-90f1-41b626890f76.png">

Thanks,
Jose
